using DataMigrationAssistant.Core.Models;

namespace DataMigrationAssistant.Core.Normalization;

public sealed class ValidationScenarioNormalizationRule : IDeterministicNormalizationRule
{
    // All of these must be present for this rule to trigger.
    // Detection is based solely on normalized column names — not file names or sheet names.
    private static readonly IReadOnlyList<string> RequiredColumns =
    [
        "validation_scenario_id",
        "validation_scenario_label",
        "validation_scenario_logic",
        "system_element_type",
        "element_sub_type",
        "element_rule_1",
    ];

    // Optional columns that belong to the parent (gtn_scenarios) entity.
    // IMPORTANT: none of these end in "_id". If any source column ending in "_id" were placed in
    // gtn_scenarios.SourceColumns, the NormalizationSqlGeneratorService suffix-match logic
    // (_id → validation_scenario_id) would steal that value for the synthetic `id` PK instead of
    // letting the auto-sequence run. validation_scenario_id is therefore kept out of SourceColumns
    // and is resolved by step-1 exact-name-match instead.
    private static readonly IReadOnlyList<string> ScenarioOptionalCols =
    [
        "group",
        "validation_scenario_label",
        "validation_scenario_logic",
        "validation_scenario_rule_platform_data_points",
        "ee_status",
        "manually_validation_by_ov_required",
        "system_validated",
    ];

    // Optional columns for the child (gtn_scenario_settings) entity that become both
    // ProposedColumns and SourceColumns. None end in "_id" so the `id` PK auto-sequence is safe.
    private static readonly IReadOnlyList<string> SettingsOptionalCols =
    [
        "system_element_type",
        "element_sub_type",
        "element_rule_1",
        "element_rule_2",
        "element_rule_3",
    ];

    public bool CanHandle(NormalizationRequest request)
    {
        var sheetColumns = SheetColumnSet(request);
        return RequiredColumns.All(col => sheetColumns.Contains(col));
    }

    public NormalizationProposal Apply(NormalizationRequest request)
    {
        var sheetColumns = SheetColumnSet(request);

        // ── gtn_scenarios ────────────────────────────────────────────────────────
        // Surrogate PK: id INTEGER (auto-sequence starting at 101).
        // Business key: validation_scenario_id TEXT NOT NULL — always present (required for
        //   detection) and resolved at seed time via step-1 exact-name-match, not SourceColumns.
        var scenariosCols = new List<ProposedColumn>
        {
            new() { Name = "id",                    PostgresType = "INTEGER", IsNullable = false, IsPrimaryKey = true },
            new() { Name = "validation_scenario_id", PostgresType = "TEXT",    IsNullable = false },
        };

        var scenariosSource = new List<string>();

        foreach (var col in ScenarioOptionalCols)
        {
            if (!sheetColumns.Contains(col)) continue;
            scenariosCols.Add(new ProposedColumn { Name = col, PostgresType = "TEXT", IsNullable = true });
            scenariosSource.Add(col);
        }

        // ── gtn_scenario_settings ────────────────────────────────────────────────
        // Surrogate PK: id INTEGER (auto-sequence starting at 1001).
        // Integer FK:   gtn_scenario_id INTEGER → gtn_scenarios(id). Marked nullable so
        //   NormalizationSqlGeneratorService emits NULL in the seed rather than erroring out —
        //   the generator cannot perform cross-table ID look-ups.
        // Trace column: validation_scenario_id TEXT (optional) resolved by step-1 exact-name-match;
        //   kept out of SourceColumns so the `_id` suffix does not redirect to it for the `id` PK.
        var settingsCols = new List<ProposedColumn>
        {
            new() { Name = "id",              PostgresType = "INTEGER", IsNullable = false, IsPrimaryKey = true },
            new() { Name = "gtn_scenario_id", PostgresType = "INTEGER", IsNullable = true,
                    ForeignKeyTo = "gtn_scenarios(id)" },
        };

        if (sheetColumns.Contains("validation_scenario_id"))
            settingsCols.Add(new ProposedColumn { Name = "validation_scenario_id", PostgresType = "TEXT", IsNullable = true });

        var settingsSource = new List<string>();

        foreach (var col in SettingsOptionalCols)
        {
            if (!sheetColumns.Contains(col)) continue;
            settingsCols.Add(new ProposedColumn { Name = col, PostgresType = "TEXT", IsNullable = true });
            settingsSource.Add(col);
        }

        return new NormalizationProposal
        {
            Reasoning = "Generated by deterministic validation scenario rule because the sheet " +
                        "contains validation scenario and pay element configuration columns.",
            Tables =
            [
                new ProposedTable
                {
                    TableName         = "gtn_scenarios",
                    Columns           = scenariosCols,
                    SourceColumns     = scenariosSource,
                    SeedSequenceStart = 101,
                },
                new ProposedTable
                {
                    TableName         = "gtn_scenario_settings",
                    Columns           = settingsCols,
                    SourceColumns     = settingsSource,
                    SeedSequenceStart = 1001,
                },
            ],
        };
    }

    private static HashSet<string> SheetColumnSet(NormalizationRequest request) =>
        request.SheetPreview.Columns
            .Select(c => c.SnakeCaseName)
            .ToHashSet(StringComparer.OrdinalIgnoreCase);
}
